package com.jimi.bm.parser.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGisCard<M extends BaseGisCard<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setCardId(java.lang.String cardId) {
		set("card_id", cardId);
		return (M) this;
	}


	public java.lang.String getCardId() {
		return getStr("card_id");
	}


	public M setImei(java.lang.String imei) {
		set("imei", imei);
		return (M) this;
	}


	public java.lang.String getImei() {
		return getStr("imei");
	}


	public M setReceiveTime(java.util.Date receiveTime) {
		set("receive_time", receiveTime);
		return (M) this;
	}


	public java.util.Date getReceiveTime() {
		return get("receive_time");
	}

}
