package com.jimi.bm.parser.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLocation<M extends BaseLocation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setBusId(java.lang.Integer busId) {
		set("bus_id", busId);
		return (M) this;
	}


	public java.lang.Integer getBusId() {
		return getInt("bus_id");
	}


	public M setRecvTime(java.util.Date recvTime) {
		set("recv_time", recvTime);
		return (M) this;
	}


	public java.util.Date getRecvTime() {
		return get("recv_time");
	}


	public M setLocatedTime(java.util.Date locatedTime) {
		set("located_time", locatedTime);
		return (M) this;
	}


	public java.util.Date getLocatedTime() {
		return get("located_time");
	}


	public M setLocationTypeId(java.lang.Integer locationTypeId) {
		set("location_type_id", locationTypeId);
		return (M) this;
	}


	public java.lang.Integer getLocationTypeId() {
		return getInt("location_type_id");
	}


	public M setReportModeId(java.lang.Integer reportModeId) {
		set("report_mode_id", reportModeId);
		return (M) this;
	}


	public java.lang.Integer getReportModeId() {
		return getInt("report_mode_id");
	}


	public M setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
		return (M) this;
	}


	public java.lang.String getLatitude() {
		return getStr("latitude");
	}


	public M setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
		return (M) this;
	}


	public java.lang.String getLongitude() {
		return getStr("longitude");
	}


	public M setSpeed(java.lang.Integer speed) {
		set("speed", speed);
		return (M) this;
	}


	public java.lang.Integer getSpeed() {
		return getInt("speed");
	}


	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M) this;
	}


	public java.lang.String getAddress() {
		return getStr("address");
	}


	public M setAmapAddress(java.lang.String amapAddress) {
		set("amap_address", amapAddress);
		return (M) this;
	}


	public java.lang.String getAmapAddress() {
		return getStr("amap_address");
	}


	public M setAmapLatitude(java.lang.String amapLatitude) {
		set("amap_latitude", amapLatitude);
		return (M) this;
	}


	public java.lang.String getAmapLatitude() {
		return getStr("amap_latitude");
	}


	public M setAmapLongitude(java.lang.String amapLongitude) {
		set("amap_longitude", amapLongitude);
		return (M) this;
	}


	public java.lang.String getAmapLongitude() {
		return getStr("longitude");
	}
}
