package com.jimi.bm.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBusFlow<M extends BaseBusFlow<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setLocationId(java.lang.Integer locationId) {
		set("location_id", locationId);
		return (M) this;
	}


	public java.lang.Integer getLocationId() {
		return getInt("location_id");
	}


	public M setIncomeNum(java.lang.Integer incomeNum) {
		set("income_num", incomeNum);
		return (M) this;
	}


	public java.lang.Integer getIncomeNum() {
		return getInt("income_num");
	}


	public M setOutcomeNum(java.lang.Integer outcomeNum) {
		set("outcome_num", outcomeNum);
		return (M) this;
	}


	public java.lang.Integer getOutcomeNum() {
		return getInt("outcome_num");
	}


	public M setSumNum(java.lang.Integer sumNum) {
		set("sum_num", sumNum);
		return (M) this;
	}


	public java.lang.Integer getSumNum() {
		return getInt("sum_num");
	}


	public M setBusId(java.lang.Integer busId) {
		set("bus_id", busId);
		return (M) this;
	}


	public java.lang.Integer getBusId() {
		return getInt("bus_id");
	}

}
