package com.jimi.bm.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBus<M extends BaseBus<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setImei(java.lang.String imei) {
		set("imei", imei);
		return (M) this;
	}


	public java.lang.String getImei() {
		return getStr("imei");
	}


	public M setLastPingTime(java.util.Date lastPingTime) {
		set("last_ping_time", lastPingTime);
		return (M) this;
	}


	public java.util.Date getLastPingTime() {
		return get("last_ping_time");
	}


	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M) this;
	}


	public java.lang.String getPlate() {
		return getStr("plate");
	}


	public M setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
		return (M) this;
	}


	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

}
