package com.jimi.bm.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStationGroupBind<M extends BaseStationGroupBind<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setStationId(java.lang.Integer stationId) {
		set("station_id", stationId);
		return (M) this;
	}


	public java.lang.Integer getStationId() {
		return getInt("station_id");
	}


	public M setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
		return (M) this;
	}


	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

}
