package com.jimi.bm.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStation<M extends BaseStation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setName(java.lang.String name) {
		set("name", name);
		return (M) this;
	}


	public java.lang.String getName() {
		return getStr("name");
	}


	public M setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
		return (M) this;
	}


	public java.lang.String getLatitude() {
		return getStr("latitude");
	}


	public M setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
		return (M) this;
	}


	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

	
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M) this;
	}


	public java.lang.Integer getType() {
		return getInt("type");
	}
}
