package com.jimi.bm.parser.model;

import com.jimi.bm.parser.model.base.BaseGisCard;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GisCard extends BaseGisCard<GisCard> {

	public static final GisCard dao = new GisCard().dao();
}
