package com.jimi.bm.parser.model;

import com.jimi.bm.parser.model.base.BaseTcpPack;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TcpPack extends BaseTcpPack<TcpPack> {

	public static final TcpPack dao = new TcpPack().dao();
}
