package com.jimi.bm.receiver.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTcpPack<M extends BaseTcpPack<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setImei(java.lang.String imei) {
		set("imei", imei);
		return (M) this;
	}


	public java.lang.String getImei() {
		return getStr("imei");
	}


	public M setContent(java.lang.String content) {
		set("content", content);
		return (M) this;
	}


	public java.lang.String getContent() {
		return getStr("content");
	}


	public M setReceiveTime(java.util.Date receiveTime) {
		set("receive_time", receiveTime);
		return (M) this;
	}


	public java.util.Date getReceiveTime() {
		return get("receive_time");
	}


	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M) this;
	}


	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
