export const tableColumns = () => [
  // {prop: "type", label: "", width: "auto"},
  // {prop: "groupId", label: "", width: "auto"},
  // {prop: "groupName", label: "线路", width: "auto"},
  // {prop: "numPlate", label: "车牌", width: "auto",},
  // {prop: "imei", label: "IMEI号", width: "auto"},
  {prop: "direction", label: "方向", width: "auto"},
  {prop: "locatedTime", label: "定位时间", width: "auto", sortable: true},
  // {prop: "recvTime", label: "", width: "auto"},
  {prop: "speed", label: "速度", width: "auto"},
  {prop: "lng", label: "GPS经度", width: "auto"},
  {prop: "lat", label: "GPS纬度", width: "auto"},
  {prop: "location", label: "位置", width: "auto"},
  // {prop: "locationType", label: "", width: "auto"},
  // {prop: "locationTypeString", label: "", width: "auto"},
  // {prop: "reportMode", label: "", width: "auto"},
  // {prop: "reportModeString", label: "", width: "auto"},
  // {prop: "status", label: "", width: "auto"},
  // {prop: "statusString", label: "", width: "auto"},
  {prop: "upCount", label: "上车人数", width: "auto"},
  {prop: "downCount", label: "下车人数", width: "auto"},
  {prop: "total", label: "剩余人数", width: "auto"},
]