package com.jimi.bm.server.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;


/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bus", "id", Bus.class);
		arp.addMapping("bus_flow", "id", BusFlow.class);
		arp.addMapping("bus_group", "id", BusGroup.class);
		arp.addMapping("location", "id", Location.class);
		arp.addMapping("location_type", "id", LocationType.class);
		arp.addMapping("report_mode", "id", ReportMode.class);
		arp.addMapping("station", "id", Station.class);
		arp.addMapping("station_group_bind", "id", StationGroupBind.class);
	}
}
