package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseBus;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bus extends BaseBus<Bus> {

	public static final Bus dao = new Bus().dao();
}
