package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseBusFlow;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusFlow extends BaseBusFlow<BusFlow> {

	public static final BusFlow dao = new BusFlow().dao();
}
