package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseBusGroup;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusGroup extends BaseBusGroup<BusGroup> {

	public static final BusGroup dao = new BusGroup().dao();
}
