package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseLocationType;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LocationType extends BaseLocationType<LocationType> {

	public static final LocationType dao = new LocationType().dao();
}
