package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseLocation;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Location extends BaseLocation<Location> {

	public static final Location dao = new Location().dao();
}
