package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseReportMode;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportMode extends BaseReportMode<ReportMode> {

	public static final ReportMode dao = new ReportMode().dao();
}
