package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseStation;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Station extends BaseStation<Station> {

	public static final Station dao = new Station().dao();
}
