package com.jimi.bm.server.model;

import com.jimi.bm.server.model.base.BaseStationGroupBind;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StationGroupBind extends BaseStationGroupBind<StationGroupBind> {

	public static final StationGroupBind dao = new StationGroupBind().dao();
}
